### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by asbjornenge** [jgoux/resolvify#1]
Hi there,

Just a little friendly reminder to publish this :smile: If you are pressed for time I'll be happy to put together a PR for you? :+1:

**Comment by jgoux** [comment]
Thanks to remind me, and sorry to forget !
I'm writing the minimal HOW TO and then I push it in a few minutes. :)
I'll let you make the fix for the CLI parameters once it'll online ;)

**Comment by jgoux** [comment]
You can now make the PR, then I'll publish it. :+1:

**Comment by asbjornenge** [comment]
@jgoux alright, I'm getting close. Take a look [here](https://github.com/asbjornenge/resolvify/tree/cli-params). I also added some tests :+1: One thing I'm a little confused about is the fact that <code>path.dirname(opts.file)</code> is used as the basedir. What is the reasoning behind that? Should it not be <code>__dirname</code>? Tests work with both.

**Comment by jgoux** [comment]
If test work both, let's remove the path dependency. I didn't use __dirname often. :)
Seems good to me, thanks for your help !

**Comment by asbjornenge** [comment]
@jgoux cool :smile: I'll clean up a few things and make a PR shortly :+1:

**Comment by jgoux** [comment]
Well done ! https://www.npmjs.com/package/resolvify

**Comment by asbjornenge** [comment]
@jgoux awesome! Thanks :tada:
